# Generated by Django 5.2.8 on 2026-06-20 07:08

import django.db.models.deletion
import registration.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=100, verbose_name='Nom')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('birth_place', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu de naissance')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('grade', models.PositiveIntegerField(choices=[(1, 'petite section'), (2, 'moyenne section'), (3, 'grande section'), (4, 'CP'), (5, 'CE1'), (6, 'CE2'), (7, 'CM1'), (8, 'CM2')], default=1, verbose_name='Grade')),
                ('family_situation', models.CharField(blank=True, choices=[('married_or_cohabiting', 'Mariés ou concubins'), ('divorced_or_separated', 'Divorcés ou séparés'), ('single_parent', 'Parent isolé')], max_length=30, null=True, verbose_name='Situation familiale')),
                ('siblings_brothers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de frères')),
                ('siblings_sisters', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de sœurs')),
                ('siblings_names', models.CharField(blank=True, max_length=500, null=True, verbose_name='Prénoms des frères et sœurs')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
            },
        ),
        migrations.CreateModel(
            name='RegistrationCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Année scolaire')),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
            },
        ),
        migrations.CreateModel(
            name='LegalRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parametres')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom')),
                ('lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('phone_home', models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone fixe')),
                ('phone_mobile', models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone portable')),
                ('phone_work', models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone travail')),
                ('profession', models.CharField(blank=True, max_length=200, null=True, verbose_name='Profession')),
                ('has_parental_authority', models.BooleanField(blank=True, null=True, verbose_name='Autorité parentale')),
                ('insurance_reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='Référence assurance')),
                ('coordinates_sharing_authorized', models.BooleanField(blank=True, null=True, verbose_name='Autorisation de diffusion des coordonnées')),
                ('pool_accompaniment', models.BooleanField(default=False, verbose_name='Accompagnement piscine')),
                ('pool_attestation', models.FileField(blank=True, null=True, upload_to=registration.models.UUIDUploadTo('pool_attestations'), verbose_name='Attestation natation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Représentant légal',
                'verbose_name_plural': 'Représentants légaux',
            },
        ),
        migrations.CreateModel(
            name='RegistrationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parametres')),
                ('document', models.FileField(blank=True, null=True, upload_to=registration.models.UUIDUploadTo('registration_documents'), verbose_name='Document')),
                ('document_2', models.FileField(blank=True, null=True, upload_to=registration.models.UUIDUploadTo('registration_documents'), verbose_name='Document 2')),
                ('document_3', models.FileField(blank=True, null=True, upload_to=registration.models.UUIDUploadTo('registration_documents'), verbose_name='Document 3')),
                ('document_4', models.FileField(blank=True, null=True, upload_to=registration.models.UUIDUploadTo('registration_documents'), verbose_name='Document 4')),
                ('document_5', models.FileField(blank=True, null=True, upload_to=registration.models.UUIDUploadTo('registration_documents'), verbose_name='Document 5')),
                ('document_6', models.FileField(blank=True, null=True, upload_to=registration.models.UUIDUploadTo('registration_documents'), verbose_name='Document 6')),
                ('document_7', models.FileField(blank=True, null=True, upload_to=registration.models.UUIDUploadTo('registration_documents'), verbose_name='Document 7')),
                ('document_8', models.FileField(blank=True, null=True, upload_to=registration.models.UUIDUploadTo('registration_documents'), verbose_name='Document 8')),
                ('document_9', models.FileField(blank=True, null=True, upload_to=registration.models.UUIDUploadTo('registration_documents'), verbose_name='Document 9')),
                ('document_10', models.FileField(blank=True, null=True, upload_to=registration.models.UUIDUploadTo('registration_documents'), verbose_name='Document 10')),
                ('vaccination_document', models.FileField(blank=True, null=True, upload_to=registration.models.UUIDUploadTo('vaccination_documents'), verbose_name='Carnet de santé / attestation vaccinale')),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to=registration.models.UUIDUploadTo('insurance_documents'), verbose_name="Attestation d'assurance")),
                ('divorce_judgment', models.FileField(blank=True, null=True, upload_to=registration.models.UUIDUploadTo('divorce_judgments'), verbose_name='Jugement de divorce/séparation')),
                ('photo', models.FileField(blank=True, null=True, upload_to=registration.models.UUIDUploadTo('pupil_photos'), verbose_name="Photo d'identité")),
                ('other_vaccines', models.TextField(blank=True, null=True, verbose_name='Autres vaccinations')),
                ('diseases_history', models.JSONField(blank=True, default=dict, help_text='Dict des maladies antérieures (angine, asthme, etc.)', verbose_name='Antécédents médicaux')),
                ('samu_authorized', models.BooleanField(blank=True, null=True, verbose_name='Autorisation appel SAMU/pompiers')),
                ('emergency_contacts', models.JSONField(blank=True, default=list, verbose_name='Personnes à prévenir en urgence')),
                ('allergies_info', models.TextField(blank=True, null=True, verbose_name='Allergies / autres informations médicales')),
                ('school_trips_authorized', models.BooleanField(blank=True, null=True, verbose_name='Autorisation sortie pédagogique')),
                ('doctor_name_phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Médecin traitant (nom et numéro)')),
                ('image_rights_authorized', models.BooleanField(blank=True, null=True, verbose_name="Droit à l'image")),
                ('authorized_pickup_persons', models.JSONField(blank=True, default=list, verbose_name="Personnes autorisées à venir chercher l'enfant")),
                ('charter_accepted', models.BooleanField(default=False, verbose_name='Charte et règlement intérieur acceptés')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Dossier clôturé')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationcampaign', verbose_name='Campaign')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.pupil', verbose_name='Pupil')),
            ],
            options={
                'verbose_name': "Dossier d'inscription",
                'verbose_name_plural': "Dossiers d'inscriptions",
            },
        ),
        migrations.CreateModel(
            name='RegistrationSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=100, verbose_name='Nom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Gestionnaire des inscriptions',
                'verbose_name_plural': 'Gestionnaires des inscriptions',
            },
        ),
        migrations.CreateModel(
            name='PupilLegalRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.legalrepresentative', verbose_name='Representative')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.pupil', verbose_name='Pupil')),
            ],
            options={
                'verbose_name': 'Lien de parenté',
                'verbose_name_plural': 'Liens de parentés',
                'constraints': [models.UniqueConstraint(fields=('pupil', 'legal_representative'), name='unique_pupil_legal_representative')],
            },
        ),
    ]
