# Generated by Django 5.2.8 on 2026-03-13 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=100, verbose_name='Nom')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('grade', models.PositiveIntegerField(choices=[('PS', 'petite section'), ('MS', 'moyenne section'), ('GS', 'grande section'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2')], default='PS', verbose_name='Grade')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
            },
        ),
        migrations.CreateModel(
            name='RegistrationCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Année scolaire')),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
            },
        ),
        migrations.CreateModel(
            name='LegalRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parametres')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Représentant légal',
                'verbose_name_plural': 'Représentants légaux',
            },
        ),
        migrations.CreateModel(
            name='PupilLegalRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.legalrepresentative', verbose_name='Representative')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.pupil', verbose_name='Pupil')),
            ],
            options={
                'verbose_name': 'Lien de parenté',
                'verbose_name_plural': 'Liens de parentés',
            },
        ),
        migrations.CreateModel(
            name='RegistrationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parametres')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.registrationcampaign', verbose_name='Campaign')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.pupil', verbose_name='Pupil')),
            ],
            options={
                'verbose_name': "Dossier d'inscription",
                'verbose_name_plural': "Dossiers d'inscriptions",
            },
        ),
        migrations.CreateModel(
            name='RegistrationSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='Prénom')),
                ('lastname', models.CharField(max_length=100, verbose_name='Nom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Gestionnaire des inscriptions',
                'verbose_name_plural': 'Gestionnaires des inscriptions',
            },
        ),
    ]
