# Generated by Django 5.2.8 on 2026-03-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='grade',
            field=models.PositiveIntegerField(choices=[(1, 'petite section'), (2, 'moyenne section'), (3, 'grande section'), (4, 'CP'), (5, 'CE1'), (6, 'CE2'), (7, 'CM1'), (8, 'CM2')], default=1, verbose_name='Grade'),
        ),
    ]
