# Generated by Django 5.2.8 on 2026-05-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registrationfile_document'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pupillegalrepresentative',
            constraint=models.UniqueConstraint(fields=('pupil', 'legal_representative'), name='unique_pupil_legal_representative'),
        ),
    ]
