# Generated by Django 5.2.8 on 2026-05-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_pupil_legal_representative_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalrepresentative',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='coordinates_sharing_authorized',
            field=models.BooleanField(blank=True, null=True, verbose_name='Autorisation de diffusion des coordonnées'),
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='has_parental_authority',
            field=models.BooleanField(blank=True, null=True, verbose_name='Autorité parentale'),
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='insurance_reference',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Référence assurance'),
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='phone_home',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone fixe'),
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone portable'),
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='phone_work',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone travail'),
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='pool_accompaniment',
            field=models.BooleanField(default=False, verbose_name='Accompagnement piscine'),
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='pool_attestation',
            field=models.FileField(blank=True, null=True, upload_to='pool_attestations/', verbose_name='Attestation natation'),
        ),
        migrations.AddField(
            model_name='legalrepresentative',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='birth_place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='family_situation',
            field=models.CharField(blank=True, choices=[('married_or_cohabiting', 'Mariés ou concubins'), ('divorced_or_separated', 'Divorcés ou séparés'), ('single_parent', 'Parent isolé')], max_length=30, null=True, verbose_name='Situation familiale'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='siblings_brothers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de frères'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='siblings_sisters',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de sœurs'),
        ),
        migrations.AddField(
            model_name='registrationfile',
            name='allergies_info',
            field=models.TextField(blank=True, null=True, verbose_name='Allergies / autres informations médicales'),
        ),
        migrations.AddField(
            model_name='registrationfile',
            name='authorized_pickup_persons',
            field=models.JSONField(blank=True, default=list, verbose_name="Personnes autorisées à venir chercher l'enfant"),
        ),
        migrations.AddField(
            model_name='registrationfile',
            name='charter_accepted',
            field=models.BooleanField(default=False, verbose_name='Charte et règlement intérieur acceptés'),
        ),
        migrations.AddField(
            model_name='registrationfile',
            name='diseases_history',
            field=models.JSONField(blank=True, default=dict, help_text='Dict des maladies antérieures (angine, asthme, etc.)', verbose_name='Antécédents médicaux'),
        ),
        migrations.AddField(
            model_name='registrationfile',
            name='divorce_judgment',
            field=models.FileField(blank=True, null=True, upload_to='divorce_judgments/', verbose_name='Jugement de divorce/séparation'),
        ),
        migrations.AddField(
            model_name='registrationfile',
            name='doctor_name_phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Médecin traitant (nom et numéro)'),
        ),
        migrations.AddField(
            model_name='registrationfile',
            name='emergency_contacts',
            field=models.JSONField(blank=True, default=list, verbose_name='Personnes à prévenir en urgence'),
        ),
        migrations.AddField(
            model_name='registrationfile',
            name='image_rights_authorized',
            field=models.BooleanField(blank=True, null=True, verbose_name="Droit à l'image"),
        ),
        migrations.AddField(
            model_name='registrationfile',
            name='insurance_document',
            field=models.FileField(blank=True, null=True, upload_to='insurance_documents/', verbose_name="Attestation d'assurance"),
        ),
        migrations.AddField(
            model_name='registrationfile',
            name='other_vaccines',
            field=models.TextField(blank=True, null=True, verbose_name='Autres vaccinations'),
        ),
        migrations.AddField(
            model_name='registrationfile',
            name='samu_authorized',
            field=models.BooleanField(blank=True, null=True, verbose_name='Autorisation appel SAMU/pompiers'),
        ),
        migrations.AddField(
            model_name='registrationfile',
            name='school_trips_authorized',
            field=models.BooleanField(blank=True, null=True, verbose_name='Autorisation sortie pédagogique'),
        ),
        migrations.AddField(
            model_name='registrationfile',
            name='vaccination_document',
            field=models.FileField(blank=True, null=True, upload_to='vaccination_documents/', verbose_name='Carnet de santé / attestation vaccinale'),
        ),
    ]
