# Generated by Django 5.2.8 on 2026-06-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_add_registration_form_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationfile',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Dossier clôturé'),
        ),
    ]
